@host = http://localhost
@port = 5010
@token = CfDJ8Lc1daO1W0ZDsZE62zNYJ4LR-atGrtdeiKA__bpAVMhbTVdffb4Vk2vGkkzIgjy8S4DevLPvzjOH8kHlnk2Cc4iTHJEsUGhKjzXacMjBdNS2wnJ4oQP9FAdcKdRaViMJv88LvZq-GLsebJjKeCq71fhMYMuzNHUhWsEISc7KUlj-m0RgMYi1ZdvBHkDJ0-eN2wxQr5MDOtxlGiFSNhBveLmM4fVouE1PDEUczvKMw8y0_4Rio4_zrKhyncYiIDDkdDGW2bae1t2U79up9GjgFY_t-eDzKqrs-fduD2g8EMepcQdeidDRs3vo4lBnw1-JuDmqypqSYxzLTBdLqiRxVgJOf7ONT2ZNNL_6Du4YM2pFhrm6Ypfk9PbWG_rl-rJIQ_nbZezd9PHlEiV5WbO3i4qytdv9hP-p-4weuZAhHFbph89CoChiD8DKeP-0dDMjtsTLzNF5nmCq64uEhPXGwigWwosSbZsRzPUtT3q-8YpWFTJrfVvbfAcgfCEY7I95ULBDu6XUOfTMeK83d5Y4frMmjRXfXcEXJtD8uRcJH05Mmf_VXYOzrr2Jb40KFFkWAxSnkzX7R6BXyQ0mxvp4v0QVaec6FcH3gyIAL7vepsdx4tJ91PJ2CFLUrrEvLklrQNtBe_-_JNmUx3GEy2uVU-Tt2FGO9OLQR44NmdN9VOY5V2g5NM6lqVTKpW__PMeiYGf-BGppV04T-HH-kxB8HW67MmlTWKz0kj44TV2DwkGMTcADyBY486fvDO6wg7GnbzpcfPzHlcwZLkstPm4Q2nrmryuRXMmEiwE6S7EWEh0q
@Restaurants.API_HostAddress = https://localhost:7194

GET {{Restaurants.API_HostAddress}}/api/restaurants
#Authorization : Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Spicy Delights3",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name": "Sample Update",
  "Description": "Sample Des",
  "HasDelivery": true 
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese",
    "Description": "Classic Italian pasta with dish with rich meat sauce",
    "Price": 12.99,
    "KiloCalories": 750
}

###

@restaurantId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@disheId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{disheId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}
