@host = http://localhost
@port = 5010
@token = CfDJ8Lc1daO1W0ZDsZE62zNYJ4JVTj1nrddcHaHk-UBXQXNUo8Sf5t_MrF7I-RrJFyUXIzinlUksOI19pzeKKs78TL6VdcyKk578S5zLz4Jj7q5agJ_PZOx9xs-oFf_gKJZbNgpA3BaP_GxVTzNrENOIjz4bsYBG_U01KsSqBnP2aJjKToFhaBSMDnY28sRdjkSZ2BNf6HMZA6OVaQJWXdLiBMo1rOR2KIkupr9vV-DmekckdT8SaMF_ymz3K-sL3IaN2I_0xs8a1vIe-qvxHez9_wUo_b70pIuj0ZVYBQe1vzWcycBDLFvpOwhsU2DVwI1hTWualVUiyXXSWq5i90g3KISIUpQ647xrTTeR6XBfjmuL45ocP6DxOw3AdvsQqy9lWpH7lfPOvr1ppfEstqOVlBMIiqr1IUTydbILRewfCzVP9M96QdYfyE9KnCOWZxtUHDSq1iYoCD3ZAbqiYizBw9r-DgdEJonBfIVpttHOiMTbekNRm1IFIKE3XcZshpPesfG3oLfwWJtSkNCu8HPHjWvwWbikgyflF5O5LF7xkZZ112I7teCr6dDXCR-ESfQ7XkIMXU-n_WLf4qsv-2DZpby5DcNzQtkyRpN2a6nQVVsER9FGT2-JCFtfrukrdRaixbCtmhGexKe_QPC2q5Ac42y589EiVZ1yd4KFBYqFJ1tmnlXPhw0EQ74fwCVIOjA3zGhm4NF3LGqayrs-_lVFRK8jwBiBnVbafJsKv9syZE_CsYiCCkew4PrvgHhN3XUkxo0gcQNIxSaPOTqUxbQCVBodi-Zvol3_499W_pJunmLk
@Restaurants.API_HostAddress = https://localhost:7194

GET {{Restaurants.API_HostAddress}}/api/restaurants?seachPhrase=&pageSize=4&pageNumber=1&sortBy=Name&sortDirection=Descending

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization : Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Spicy Delights3",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Updated Name",
  "Description": "Sample Des",
  "HasDelivery": true 
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese",
    "Description": "Classic Italian pasta with dish with rich meat sauce",
    "Price": 12.99,
    "KiloCalories": 750
}

###

@restaurantId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Authorization : Bearer {{token}}

###

@disheId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{disheId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization : Bearer {{token}}

{
    "Nationality" : "French",
    "DateOfBirth" : "2001-01-04"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "UserMail": "owner2@test.com",
  "Rolename": "Owner"
}

###
