@host = http://localhost
@port = 5010
@token = CfDJ8Lc1daO1W0ZDsZE62zNYJ4KKjopkNiKddMPY_pH1eAahTgRqLNq3d0yHhKsbN9mxv9U-TJs9rDnmYje3fRs6pDtPQayMZ_pAvyJHxKuLvpePKaknnAF_YJVAE5jpekHE0usUs0g0RTlPVj2qmC6Mny5OUafEDw-bha5GOsf6XG7e86OaSnSK1-upnUuYWYjPLSMw30BO0GhNcR36bozy-m5rOase1ltx1JcCYyoZFe2gzL_Vf90Fr_rFgVJ-mB-JI22Ggh8MNS2HkTu4NjvcS5QbaudLstGO7Nx_Pdn8vY39B2vXEBYpnmS3YZFbiVuL3khj-UbnrpwqQ2f69-IL92S6WS2xuK739i9-qAo9H3r0L2Cjg1aF3JQ9F8nJfC941i-rsBxp2w7_ExM0f6OddamZyBKy-00x8UP4eNgg7rBgrcHKWcRgbYYehw-t0udkDzwGdBpZDKXbLVoSoc6TSYzgRcZ3TN2OVZOlqdMQ57iIGl9MYj0lNq7cHRBJDHXuQqLl6HEqDneVMD3XkPuVo3PoVgveFrNzuL_n7QbkjipPoacEcJpxyDKiqMIRssnt1q-uGNBlrIzfjgtXEO2GzxzRQvZBrEZgwPjvj4WTABU0T_SHR5o1vB8LMawEjFQ_Nu-mU5eZ6gK1mOxlnqkTBWwxChHm6zIAsJ-XtmFVrC24hex3ZXuGJ2Bhaj8McJwEFAaCrWeDjE8Rms_F9h-iFvBmm_49xSABthw_WIsrCNekKHsFRaVBMZD6KzyM7zGKcoHo-giBPZKvYxFn1whvUQA
@Restaurants.API_HostAddress = https://localhost:7194

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization : Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Spicy Delights3",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name": "Sample Update",
  "Description": "Sample Des",
  "HasDelivery": true 
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese",
    "Description": "Classic Italian pasta with dish with rich meat sauce",
    "Price": 12.99,
    "KiloCalories": 750
}

###

@restaurantId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@disheId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{disheId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization : Bearer {{token}}

{
    "Nationality" : "French",
    "DateOfBirth" : "2001-01-04"
}

###
